compressionLevel: 0

enableGlobalCache: false

nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org'
npmPublishRegistry: 'https://europe-west1-npm.pkg.dev/ornikar-images/npm-packages/'

npmScopes:
  ornikar:
    npmRegistryServer: 'https://europe-west1-npm.pkg.dev/ornikar-images/npm-packages/'
    npmAlwaysAuth: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: 'https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js'
  - path: .yarn/plugins/@yarnpkg/plugin-preinstall.cjs

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
  os:
    - linux
    - darwin

yarnPath: .yarn/releases/yarn-4.3.1.cjs
